# Generated by Django 5.1.5 on 2025-01-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_themes', '0001_initial_netbox_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='base_theme',
            field=models.CharField(default='toggle', max_length=10),
        ),
    ]
