# Generated by Django 5.0.10 on 2024-12-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_themes', '0001_initial_netbox_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='base_theme',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
